### ISSUE TITLE
CSSPrimitiveValue_ConfigurablePixelsPerInch.h file not found

### ISSUE THREAD

**Issue by binbin-smile** [SVGKit/SVGKit#389] opened 2015-12-02 09:13 UTC
Hello, After I import the .a and usr folder into my project,  the error  "CSSPrimitiveValue_ConfigurablePixelsPerInch.h file not found" will appear. Other class files have the same issue. Do I need add the related files manually ？

**Comment by adamgit** [comment] 2015-12-02 09:46
No, you don't.

It sounds like your Xcode project file is corrupt. This sometimes happens
when someone does a pull request or a commit, and their copy of Xcode has
removed some of the header files. It is a severe bug in Xcode that Apple
fixed 2 years ago.

Please try a slightly earlier commit from git, and see if you have the same
problem - if not, it means one of our recent commits is broken.

**Comment by binbin-smile** [comment] 2015-12-03 03:28
I resolved this issue by adding the missing header files manually. But why it happened? In the "Build Phases"---->"Headers" section ------>"Public" group,  "CSSPrimitiveValue_ConfigurablePixelsPerInch.h" is  already included.

**Comment by adamgit** [comment] 2016-01-09 11:25
I downloaded latest version, ran locally, this did not happen.

I am testing the new Frameworks setup now, hopefully that will make bugs like this disappear forever.

I'm closing this Issue, since I can't reproduce. If I later find a reproduction, I will re-open it.

**Closed as completed by adamgit** 2016-01-09 11:25 UTC

**Comment by alexandre-g** [comment] 2016-02-08 06:56
Ran into this issue today with freshly downloaded latest version. Tried with frameworks beforehand - but only succeeded in building it for arm architecture (which renders it somewhat useless - cant run on simulators). We probably need a multi architecture build script to get that working?

**Comment by adamgit** [comment] 2016-02-08 12:18
Something seems to be wrong - frameworks should DEFINITELY auto-build
correctly, that's Apple's code and it's the whole point!

**Comment by lakario** [comment] 2016-04-13 19:57
This is happening for me on the latest commits to the 2.x branch.

**Comment by lakario** [comment] 2016-04-13 20:00
Also happening for me on the 2.0 release sources.

**Comment by adamgit** [comment] 2016-04-13 23:06
I dragged and dropped the header files from project into the "public headers" section.

Only reason I'd expect them missing is someone did a commit where Xcode had moved them out (which it used to do, but hasn't done for a very long time AFAIAA).

It seems that if you build once successfully, Xcode "figures it out" and you never see the problem again - my clean build worked fine without the headers, even though in theory it shoudn't!
