### ISSUE TITLE
CocoaPods for '2.x' broken?

### ISSUE THREAD

**Issue by btraut** [SVGKit/SVGKit#396] opened 2015-12-20 11:53 UTC
I'm trying to import SVGKit into my Swift tvOS project via CocoaPods and it's not working. I'm a newbie to both Swift development and CocoaPods, so I may be doing something wrong here.

I've added SVGKit to my podfile as such:

```
pod 'SVGKit', :git => 'https://github.com/SVGKit/SVGKit.git', :branch => '2.x'
```

There are no errors upon installation and a folder for SVGKit is created (as well as for CocoaLumberjack). But the folder for SVGKit is empty both in the project file as well as on disk. From this point, I have no idea if it actually installed properly, and if so, how to import it.

<img width="611" alt="screen shot 2015-12-20 at 3 52 21 am" src="https://cloud.githubusercontent.com/assets/967591/11917832/305945c6-a6cd-11e5-9421-2f1bc59e07bc.png">

[This post](http://stackoverflow.com/questions/25028328/how-to-put-svgkit-in-my-project#comment38926355_25028328) suggests that CocoaPods should work fine but gives no instructions. Issue #189 also asks about using SVGKit with Swift, but the instructions on that thread seem to suggest that I need to manually download/import/configure, something I was hoping CocoaPods would do for me.

Thanks in advance!

**Comment by adamgit** [comment] 2015-12-20 13:41
Just a guess, but ... should the branch be "2.x" ?

**Comment by btraut** [comment] 2015-12-20 20:24
Oh, good eye! Unfortunately, that was a copy/paste error (somehow...?). I've got it correct in my project:

```
pod 'SVGKit', :git => 'https://github.com/SVGKit/SVGKit.git', :branch => '2.x'
```

**Comment by seltzered** [comment] 2015-12-20 20:35
@btraut : I haven't duplicated this, but so far that looks like that should work, others have suggested the same thing and I made a pullreq ( https://github.com/SVGKit/SVGKit/pull/381 )  to add the same line to the readme. Oddly, I use cocoapods + the osx fork of svgkit, but don't even have an xcodeProjectData folder like you have in your screenshot, so go figure. Could you maybe try these things:

1) Try actually writing a line of `#import <SVGKit/SVGKit.h>` (or whatever the swift equivalent is of this) somewhere, does it actually build?

2) if not, check that your Pod > Headers > Build  folder has svgkit folder with headers in there.

3) I'm not sure if all the things for tvOS support have been rolled into the main branch yet, you may need to use the fork this PR is based on for the moment: https://github.com/SVGKit/SVGKit/pull/375

**Comment by btraut** [comment] 2015-12-20 20:41
> 1) Try actually writing a line of #import <SVGKit/SVGKit.h> (or whatever the swift equivalent is of this) somewhere, does it actually build?

As far as I can tell, no import statements recognize it from the Swift side. Because SVGKit is an Objective-C project, I assumed I'd need to use a bridging header, but to your second point...

> 2) if not, check that your Pod > Headers > Build folder has svgkit folder with headers in there.

No, CocoaPods didn't build a folder under Pod > Headers. There's only Pod > Headers > Private, and it contains CocoaLumberjack but no SVGKit.

> 3) I'm not sure if all the things for tvOS support have been rolled into the main branch yet, you may need to use the fork this PR is based on for the moment: #375

Oh, I was under the assumption that tvOS support had already merged in given the fact that there's a build target for it in the 2.x branch. I'll give that a shot and report back. Thanks!

**Comment by btraut** [comment] 2015-12-20 21:15
I couldn't figure out how to get the build in #375 working.

It's a bit unrelated to this thread, but I was able to build and bridge to Swift manually:
1. I downloaded the latest 2.x code manually. There's a tvOS target in this file, but I can't build it because it depends on a version of CocoaLumberjack that is too old to support tvOS.
2. I downloaded the latest version of CocoaLumberjack which does support tvOS and replaced the old version in the SVGKit project.
3. I built the tvOS version of CocoaLumberjack inside of SVGKit.
4. This finally let me build the tvOS target of SVGKit.
5. I took the SVGKit.framework and copied it into my own project.
6. I added the following to my bridging header:

```
#import <SVGKit/SVGKImage.h>
#import <SVGKit/SVGKParser.h>
#import <SVGKit/SVGKLayer.h>
#import <SVGKit/CALayerExporter.h>
#import <SVGKit/SVGKExporterNSData.h>
#import <SVGKit/SVGKExporterUIImage.h>
#import <SVGKit/SVGKImage+CGContext.h>
```
1. In my view file, I imported SVGKit as such:

```
import SVGKit
```
1. And finally, this works!

```
let outerGridSVG = SVGKImage(named: "OuterGrid.svg")
```

**Comment by adamgit** [comment] 2016-01-09 10:11
What are the two versions of Lumberjack? If it's updated considerably, can someone please try latest as a commit on its own, check its working OK, then submit a PR?

I don't want to update Lumberjack in the same commit as other changes!

**Comment by adamgit** [comment] 2016-01-10 14:52
I've now upgraded project to latest Lumberjack - with tvOS compatibility - please download latest SVGKit (2.x branch) and see if it works

**Comment by alexsmith84** [comment] 2016-01-12 09:20
Hi, I too am having difficulty getting the pod to install successfully. I also use Cocoalumberjack in my project however, and this should be completely independent, 'pod install' fails while both of these pods are disabled in my Podfile. When I say "both of these pods," I'm referring to:

pod 'CocoaLumberjack/Swift' # 2.2
AND
pod 'CocoaLumberjack', '~> 1.9' # 1.9 Objective-C

I haven't tried the lengthy approach @btraut has outlined to circumvent any current errors with either Cocoapods or the Podspec this repo may have but I may try this tomorrow as a last resort.

Lastly, I'm confused as to what @btraut changed in the Podfile to include SVGKit in his project with regard to his original post.

`pod 'SVGKit', :git => 'https://github.com/SVGKit/SVGKit.git', :branch => '2.x'`

looks identical in his first and second post. Am I missing something terribly obvious?

**Comment by adamgit** [comment] 2016-01-12 10:19
2.x branch has been using lumberjack 2 for some time now, and is currently 
on 2.1, so I think your podspec is out of date?

**Comment by tthbalazs** [comment] 2016-01-12 15:42
I also have an error using cocoapods

My podfile contains this:
`pod 'SVGKit', :git => 'https://github.com/SVGKit/SVGKit.git', :branch => '2.x'`

This is the error I get:

```
Errno::ENOENT - No such file or directory @ rb_sysopen - /project_path/Pods/SVGKit/XCodeProjectData/SVGKit-iOS/SVGKit-iOS-Prefix.pch
```

I had no problems installing previous versions (2.0.0, 1.2)

**Comment by adamgit** [comment] 2016-01-12 18:30
Cocoapods is not supported, as always.

Whatever new problems CP creates: unless you can reproduce by simply 
running the working, tested, preconfigured, provided projects .... you're 
on your own.

**Comment by alexsmith84** [comment] 2016-01-13 05:46
I have the same error as @tthbalazs

Respectfully, @adamgit, it's not at all apparent that Cocoapods is NOT supported. In fact, the README indicates that it is! I'm using the latest stable version of Cocoapods. I don't know what version this repo may be using. 0.39.0 is the latest stable version while version 1.0.0.beta.2 is currently under development and available for public testing. Are you using a beta version? What version is @JohnWong using? Anyway, the point is that in an empty project, this pod fails to install every time.

If this project doesn't support Cocoapods, then please update the README to reflect that.

**Comment by adamgit** [comment] 2016-01-13 10:37
Thanks for the idea on readme.

The install instructions don't cover CP, and I assumed it was obvious we 
don't use it - but it would be MUCH clearer if readme were explicit!

**Comment by JohnWong** [comment] 2016-01-13 10:53
@Shmaff I am using Cocoapods 0.39.0. I have found that the pch file referred in podspec file is missing. I  have created a PR to fix this issue. You may wait for this PR to be merged or try this to see if it is really fixed:

```
pod 'SVGKit', :git => 'https://github.com/JohnWong/SVGKit.git', :branch => '2.x'
```

**Comment by tthbalazs** [comment] 2016-01-13 10:59
@JohnWong I tried your fork and it works, thank you for the quick fix.

**Comment by adamgit** [comment] 2016-01-13 15:45
Looks good to me, good find. I've merged it.

**Comment by areiks** [comment] 2016-01-13 16:51
@adamgit Thank you, its working now

**Comment by alexsmith84** [comment] 2016-01-14 06:13
Thank you, @JohnWong and @adamgit

**Comment by adamgit** [comment] 2016-01-16 18:38
As I understand it ... all is now working fine with CocoaPods (now that we've upgraded to latest Lumberjack, and fixed the reference in podfile that needed updating).

Any new problems, please open new issues, but I'm closing this as Fixed.

**Closed as completed by adamgit** 2016-01-16 18:38 UTC
