### ISSUE TITLE
Conflict with Comment name

### ISSUE THREAD

**Issue by MaddTheSane** [SVGKit/SVGKit#208] opened 2014-09-05 05:02 UTC
There is a problem with SVGKit on OS C: there's a system header, located inside CarbonCore, named AIFF.h. This header has the structs needed to create an AIFF file from scratch. One of the structs is called `Comment`. This clashes with the declaration of the Comment class.

As it is, I have it so that before any other system header, I do this by including this in the prefix header:

```
#define Comment AIFFComment
#include <CoreServices/CoreServices.h> // this includes the conflicting header
#undef Comment
```

However, Swift uses modules, which forces types to have a consistent name, so the `#define` trick doesn't work. So if a Swift developer wanted to use SVGKit on OS X, it'd be near impossible.

There are a few choices that could be made to force it to work:
- Re-write SVGKit to Swift
- Re-name the class
- Have all the core DOM classes have a specific prefix/suffix.

**Comment by adamgit** [comment] 2014-09-05 15:43
Ouch.

Comment is a core DOM class. I really don't like the idea of renaming DOM 
classes.

OTOH ... We're creating the same conflict if someone ever has an 
alternative DOM implementation they want to use elsewhere in their app.

At the very least we ought to make the DOM implementation swappable.

**Comment by MaddTheSane** [comment] 2014-09-05 20:08
The naming conflict is why one of my first pull request was to change the name of the `Comment`.

Also, the issue was made when I was half-asleep, so I forgot what my third point was going to be. I remembered it now.

**Comment by adamgit** [comment] 2014-11-14 12:52
Someone has suggested using @compatibility_alias - I had _never heard of this feature_, but it seems to be supported in iOS8 / Xcode 6.x

Have you tried this? If not, can you do a quick check, see if it fixes the Comment problem with Swift too? (I'm evaluating this for use with all the DOM classes, but it would be good to know if it's going to fix Swift, or if we still need a solution there)

c.f. http://stackoverflow.com/a/14107519/153422

**Comment by zantoku** [comment] 2015-05-15 09:34
The DOM implementation declares a lot of terribly generic class names - "Comment" just being one of them. "Document", "Text", "Element" and "Node" are bad offenders too, Objective-C being not a namespaced language. All DOM classes should be prefixed.

**Comment by adamgit** [comment] 2015-05-15 09:54
You're welcome to use @compatibility_alias to make it easy _for users_ to rename the classes.

However, we are absolutely not going to break the specification simply becuase Objective-C is a poorly-designed language! As you say, those class names are "terribly generic" - so generic that they oughtn't to appear in any developer's code either :).

In practice, I have never seen a conflict in any real project. No-one uses those class names in Obj-C because it's too dangerous - so in the end, ironically, it's OK.

HOWEVER: @compatibility_alias appears to give us the best of both worlds: the library ships with the spec-compliant names, but it is a 3-second change for any developer/team to customize their copy so that it uses any namespace-in-class-name alternative they like

(i.e.: please go ahead and use it, have it default to the current names, and then submit a pull request. I haven't the time to do this, and it's not affected any projects I've worked on, so it's not been worth the effort for me)

**Comment by zantoku** [comment] 2015-05-15 11:50
Well, I wouldn't have written my comment if I hadn't encountered a conflict in a real project. Our shipping app uses some terribly-genericly named classes of our own, for good reasons, one of them being Comment. One could debate that end-user code is allowed to do that, for clarity of concept reasons.

Maybe I don't understand the @compatibility_alias directive correctly, but I don't see how it is going to help. The linker symbol _OBJC_CLASS_$_Comment needs to go away, otherwise the linker will still complain about duplicate symbols. Do you propose to rename the class in the SVGKit DOM implementation, and then establish a @compatibility_alias so you can continue to refer to "Comment" in the library code? I don't quite see the point of that.

Also consider runtime implications. When dynamically retrieving a class with NSClassFromString, which implementation is the runtime going to pick? Sorry, but @compatibility_alias seems like a bandaid, not a solution.

I hope you can see my comment in the constructive spirit it's intended to be!

**Comment by adamgit** [comment] 2015-05-15 12:02
Compatibility Alias _appears to_ solve the problem; I played around with a
blank project in xcode. Seemed to do what we wanted.

IIRC:
1. change all internal classnames to something with prefix (yes, this is
   annoying - but the DOM classes shouldn't need to be edited that often!).
2. add a header file to the SVGKit project, outside the DOM folders, that
   uses the alias to convert them all to the spec names (e.g. Comment)
3. any 3rd party can edit/replace that header file to use whatever aliases
   they prefer/need.

(IIRC! Might be wrong. If its right, then, as noted, making the DOM class
names a pain to edit is IMHO acceptable compromise: we still need to edit
htem a little, but the spec is much simpler than SVG, and I don't expect
we'll edit them much in future, so its only a small pain)

But no-one has sat down and actually experimented on the real project. So I
can't tell you if it does.

If you have a real project to test on, it would be best if you play with
this and see if you can get it to work (I suggest: make a dummy project
with only a few files to try it out and find out what the options are. If
that works better than you think, then try it on the main project and check
it still works as intended when you integrate with your current project)

**Comment by adamgit** [comment] 2015-07-01 19:05
Update: I tried it.

I discovered that Apple's compiler has some bugs in the implementation.

That makes this 10x harder to implement than it ought to be.

Closing this (because it only covers one file) and moving discussion to a general Issue covering the problem with ALL files and current workarounds / progress:

 https://github.com/SVGKit/SVGKit/issues/343

**Closed as completed by adamgit** 2015-07-01 19:05 UTC
