### ISSUE TITLE
SVGKLayer was deallocated while key value observers were still registered with it - iOS8.0

### ISSUE THREAD

**Issue by bsousa156** [SVGKit/SVGKit#214] opened 2014-09-22 11:57 UTC
Hi guys,

Thanks for the amazing work on SVGKit. 

There is a bug on iOS8.0 that makes the app crash. This also manifests with warnings on iOS7+.

When using SVGKLayeredImageView, once it gets deallocated it sends the following exception:

"**\* Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'An instance 0x7f847d8b8970 of class SVGKLayer was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x7f847d8b92a0> (
<NSKeyValueObservance 0x7f847d884570: Observer: 0x7f847d8b8970, Key path: showBorder, Options: <New: YES, Old: NO, Prior: NO> Context: 0x0, Property: 0x7f847d894250>"

While on iOS7 the same happens but it does not break the app. I'm aware of a similar issue on the observers added to the DOMTree.viewport and i'm removing those on dealloc. But it does not solve the SVGKLayer issue.

**Comment by adamgit** [comment] 2014-09-22 12:16
Pull request #212 allegedly fixes this - but it does it by silently dropping the thrown exception. I can't merge that - it MUST at least log an Info or Warning log message.

This has also been discussed in #183, #184, and #187 - but each time someone brings this up, and we push for "OK, but we need a general solution, not a hack. Have you tried this in the other cases? Do you know this works for sure, or is it just a lucky guess that works on one single file?" etc, we never hear back.

Since no-one is willing to test this properly, I'd accept:
- combine #184 and #212 : use the #184 tactic of simply moving the line of code (!), and combine it with #212's guard (that protects against "this might still crash in rare cases"), but with a DDLogWarning for those cases ... so that if this DOES NOT fully fix the problem, we still at least get a warning.

...but I don't have iOS8 so I can't even test it.

**Comment by bsousa156** [comment] 2014-09-22 13:08
Hi Adam,

Thanks for the quick response. About iOS8, don't you have xcode6/ iOS8 simulator?

**Comment by adamgit** [comment] 2014-09-22 13:11
Testing on simulator isn't enough. Simulator uses a faked version of Quartz
/ CoreGraphics / CoreAnimation. There are MAJOR differences between the sim
and device here!

There are occasional issues (and this is exactly the kind of thing!) that
only trigger on device, or only on Simulator.

**Comment by bsousa156** [comment] 2014-09-22 13:34
I get your point, but on this case the behaviour is the same on device and sim. I'm looking at the branches that you have pointed out and see if it sorts the problem.

**Comment by bsousa156** [comment] 2014-09-22 14:04
Happy to tell that uncommenting the following line in SVGKLayer.m solved the issue:

//FIXME: Apple crashes on this line, even though BY DEFINITION Apple should not be crashing: [self removeObserver:self forKeyPath:@"showBorder"];

**Comment by adamgit** [comment] 2014-09-22 14:17
Ah - so, perhaps there is a bug in iOS 7 on Apple's side (in addition to
whatever we did wrong), and they've now fixed it?

In which case, perhaps we want:
1. IF( ios8 ) ... do that line
2. ELSE ... do the @try ... catch from #212

?

(or for 2 ... move the line, as per @maddthesane's patch?)

I'm really not sure, I hate this bug - it's been fixed a bunch of times,
and each time I've tested it / committed it, it comes back again later :(

**Comment by bsousa156** [comment] 2014-09-23 10:51
On iOS7 that bug still manifests, it just does not crash the app immediately but it does leak. I suppose that removing the observer every time it's added is always a good practice.

**Comment by DinerIsmail** [comment] 2014-10-09 13:18
Hi guys!

Have you found a good fix for this?

**Comment by adamgit** [comment] 2014-10-09 14:05
When you post to this thread, you spam the inboxes of every person on it.

If your comment adds nothing, it takes away time they would have spent on improving the software.

If you're impatient for a fix, there is LOTS of info in this thread, you just need to read it and decide what to do - all the source is there, you can easily edit it yourself.

If you just wanted to be informed when the status changes, you can "subscribe to notifications" in the sidebar/navbar

**Comment by DinerIsmail** [comment] 2014-10-09 14:15
I'm sorry for that, Adam. I've tried a few ways which you explained in the thread but it doesn't seem to fix the issue for me. However, I will continue investigating the problem.

**Comment by adamgit** [comment] 2014-10-09 14:18
If you tried and it didn't work for you - that's hugely useful info for the rest of us. Might be you've found a problem no-one else has seen! Best to shout, before someone assumes "it works" and commits it :).

If it doesn't make sense, it's fine to ask for clarification - if you don't understand, then maybe the rest of us are misunderstanding each other too, and you can help us avoid screwing-up by making assumptions about each other's ideas

**Comment by adamgit** [comment] 2014-10-09 14:19
(if it doesnt work - best of all is to fork it (one-click on Github web interface), try it, and then copy/paste a link to your fork so others can run your exact code on their machine and see if they get the same problem)

**Comment by rongweiji** [comment] 2014-10-12 04:39
hi,i have same problem, i put a svgkfastimageview in my custom collectionviewcell, when i press back button for leaving  from the viewcontroller  which hold the collectionview , i got the crash ,
import Foundation

this is my custom cell code 

class SVGCell:UICollectionViewCell {

var svgcelliv:SVGKFastImageView!
    required init(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    override  init(frame: CGRect) {
        super.init(frame: frame)
        svgcelliv=SVGKFastImageView(frame: CGRect(x: 0, y: 0, width: frame.size.width, height: frame.size.height))
        svgcelliv.contentMode=UIViewContentMode.ScaleAspectFit
        contentView.addSubview(svgcelliv!)  
    }
}

this is the log 
**\* Terminating app due to uncaught exception 'NSRangeException', reason: 'Cannot remove an observer <SVGKFastImageView 0x7f8f326d42c0> for the key path "layer" from <SVGKFastImageView 0x7f8f326d42c0> because it is not registered as an observer.'
**\* First throw call stack:

i use the 2.x svgkit

thank u for helping me

**Comment by MaddTheSane** [comment] 2014-10-12 05:55
I'll look into making patch #184 more acceptable, including tests seeing if it works.

**Comment by MaddTheSane** [comment] 2014-11-27 00:41
It would seem that there's a few more bugs, in particular one related to `SVGKFastImageView`'s `initWithSVGKImage:` which can cause bugs later in execution. It ends up that `populateFromImage:` gets called twice, creating duplicate observers. Forcing the observers to only be observed once fixes the problem with `SVGKFastImageView`.

**Comment by mdwem** [comment] 2015-01-09 16:10
I am having this issue with the showBorder property.I tried uncommenting 
//FIXME: Apple crashes on this line, even though BY DEFINITION Apple should not be crashing: [self removeObserver:self forKeyPath:@"showBorder"];

This fixed the deallocating,however when i zoom in the SVGKLayeredImageView i get another crash
Terminating app due to uncaught exception 'NSRangeException', reason: 'Cannot remove an observer <SVGKLayer > for the key path "showBorder" from <SVGKLayer > because it is not registered as an observer.'
Any solution for this.This is on ios 8.1

**Comment by Waheiba** [comment] 2015-03-17 11:02
I'm not sure if this is directly related but I had a similar problem, that i think is resolved (at least same steps don't crash anymore)
**\* Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'An instance 0x7bed2340 of class SVGKLayeredImageView was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x7be0e8b0> (
<NSKeyValueObservance 0x7bed3290: Observer: 0x7c04ed40, Key path: timeIntervalForLastReRenderOfSVGFromMemory, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x7c689e30>

I commented out the line in didLoadNewResourceCreatingImageView: in the demo project
[self.contentView addObserver:self forKeyPath:@"timeIntervalForLastReRenderOfSVGFromMemory" options:0 context:nil];

From what I understood its mainly to show the time needed for rendering and parsing the file
I know the observer is removed when the observer is fired, but for the money file its not being called thus observer is never removed.

I also changed the contentView class in the xib file to SVGKLayeredImageView if its related.

**Comment by dovo329** [comment] 2015-06-27 01:49
putting this in SVGKLayer.m on the master-ARC branch latest commit lets me dismiss my viewcontroller that uses SVGKit while avoiding crash on IOS 8 as well as still allowing me to zoom in (I have an SVGImageView inside a UIScrollView) without a crash.
- (void)dealloc
  {
  @try{
      [self removeObserver:self forKeyPath:@"showBorder"];
  }@catch(id anException){
      //do nothing, obviously it wasn't attached because an exception was thrown
  }
  }

**Comment by leeirvinekezzico** [comment] 2015-08-25 16:48
I'm not sure if this is relevant to this particular issue, but...

reassigning the image property of an SVGKImageView and then releasing its parent UIView appears to produce the same result.

for example:
  self.backgroundImageView.image = self.style.backgroundImage;

After removing the above line from my code I was able to solve this crash.

**Comment by sciutand** [comment] 2015-12-02 23:55
Yes the root cause of the error is that observers are registered multiple times which causes the error when they are removed only once. We could track which key are being observed, make sure they are observed only once and remove all the registered keys.

**Comment by ghost** [comment] 2015-12-03 20:53
In my project, when we add observers in a piece of code that is called
multiple times, we first remove the observer and then add it.
Removing an observer that was not observing does not cause a crash.
This solution makes sure that the observer is only added once, without
adding complexity to the code.

On Thu, Dec 3, 2015 at 1:55 AM, Andrea Sciutto notifications@github.com
wrote:

> Yes the root cause of the error is that observers are registered multiple
> times which causes the error when they are removed only once. We could
> track which key are being observed, make sure they are observed only once
> and remove all the registered keys.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/SVGKit/SVGKit/issues/214#issuecomment-161470712.

## 

Guy, iOS Team

**Closed as completed** 2015-12-06 23:47 UTC
